# Generated by Django 4.0.4 on 2022-05-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_bookimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookImg',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='default_cover.jpg', upload_to=''),
        ),
    ]
